// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v5.29.3
// source: proto/product.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "product";

export interface CreateSampleRequest {
}

export interface CreateSampleResponse {
  success: boolean;
}

export interface GetProductInfoRequest {
  productIds: string[];
}

export interface GetProductInfoResponse {
  products: GetProductInfoResponse_ProductInfo[];
}

export interface GetProductInfoResponse_ProductInfo {
  id: string;
  name: string;
  description: string;
  price: number;
  stock: number;
}

export const PRODUCT_PACKAGE_NAME = "product";

export interface ProductServiceClient {
  createSample(request: CreateSampleRequest, metadata?: Metadata): Observable<CreateSampleResponse>;

  getProductInfo(request: GetProductInfoRequest, metadata?: Metadata): Observable<GetProductInfoResponse>;
}

export interface ProductServiceController {
  createSample(
    request: CreateSampleRequest,
    metadata?: Metadata,
  ): Promise<CreateSampleResponse> | Observable<CreateSampleResponse> | CreateSampleResponse;

  getProductInfo(
    request: GetProductInfoRequest,
    metadata?: Metadata,
  ): Promise<GetProductInfoResponse> | Observable<GetProductInfoResponse> | GetProductInfoResponse;
}

export function ProductServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createSample", "getProductInfo"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ProductService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ProductService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PRODUCT_SERVICE_NAME = "ProductService";
